### ISSUE TITLE
ImportError: cannot import name 'Filters' from 'telegram.ext'

### ISSUE THREAD

**Issue by vt107** [TheDarkW3b/instagram#12]
I got the following error when running with python 3 (macos)

```
Traceback (most recent call last):
  File "/Users/thovan/Documents/instagram/main.py", line 5, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext
ImportError: cannot import name 'Filters' from 'telegram.ext' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/telegram/ext/__init__.py)
```

**Comment by dkbosei00** [comment]
instead of `from telegram.ext import Filters` do `from telegram.ext import filters` 
also make sure you're using python-telegram-bot <=13.5 since this code was written using that version and v20 is now available.

See https://stackoverflow.com/questions/75095107/importerror-cannot-import-name-filters-from-telegram-ext

**Comment by xqll5559** [comment]
You can do that and everything works
```
pip uninstall python-telegram-bot
pip install python-telegram-bot==13.5
```

**Comment by vt107** [comment]
Hello,

It works when install python-telegram-bot 13.5. Thank a lot.

Have a nice day <3
